-- ============================================================
-- 프라임브릿지 프로덕션 DB 덤프
-- 생성: 2026-08-15T09:54:18.432Z
-- ============================================================

-- ── applications ──────────────────────────────────────────
TRUNCATE TABLE applications RESTART IDENTITY CASCADE;
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (3, '김서하', '01099439212', '개인사업자', '3천~5천만원', '운영자금', '경기도', '430219218', '현재연체:아니오, 1년이내:아니오', '{"성별":"여성","연령대":"50대","사업기간":"3년 이상","업종":"제조업","업태":"전자부품","2024년매출":"375686277","월평균매출":"7000만원","기존대출건수":"4건 이상","기존대출총잔액":"5,000만~1억원","대출종류":"담보대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-30T04:55:08.540Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (4, '지옥녀', '01095382781', '법인사업자', '5천만원~1억원', '여유자금 확보, 신규 사업 및 사업 확장, 차량 구입 (사업용)', '인천광역시', '0', '현재연체:아니오, 1년이내:아니오', '{"성별":"여성","연령대":"50대","사업기간":"3년 이상","업종":"일반사무","업태":"기장. 조정","2024년매출":"0","월평균매출":"0","기존대출건수":"1건","기존대출총잔액":"1,000만원 미만","대출종류":"개인신용대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-30T04:59:57.662Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (5, '권혜숙', '01092459066', '개인사업자', '3천~5천만원', '기존 대출 대환', '경기도', '5900', '현재연체:아니오, 1년이내:아니오', '{"성별":"여성","연령대":"40대","사업기간":"2~3년","업종":"도소매","업태":"의류","2024년매출":"5천","월평균매출":"15","기존대출건수":"3건","기존대출총잔액":"3,000~5,000만원","대출종류":"개인신용대출, 사업자대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-30T06:19:13.202Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (6, '신현봉', '01053618393', '개인사업자', '1천~3천만원', '운영자금, 시설자금 (장비·기계 구입)', '강원특별자치도', '1억', '현재연체:아니오, 1년이내:아니오', '{"성별":"남성","연령대":"50대","사업기간":"6개월~1년","업종":"소매업","업태":"휴게음식점 ","2024년매출":"7천","월평균매출":"1500만눤","기존대출건수":"2건","기존대출총잔액":"1,000~3,000만원","대출종류":"사업자대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-30T06:31:25.353Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (7, '김종대', '01053836817', '개인사업자', '1천~3천만원', '기존 대출 대환', '대구광역시', '모름', '현재연체:예, 1년이내:예', '{"성별":"남성","연령대":"60대 이상","사업기간":"3년 이상","업종":"택배","업태":"서비스업","2024년매출":"모름","월평균매출":"300","기존대출건수":"3건","기존대출총잔액":"1억원 이상","대출종류":"담보대출","현재연체":"예","1년이내연체":"예","자금용도기타":""}', 'pending', '2026-07-30T08:07:36.921Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (8, '김택선', '01054966798', '개인사업자', '1천~3천만원', '운영자금', '경기도', '약8천만', '현재연체:아니오, 1년이내:아니오', '{"성별":"남성","연령대":"60대 이상","사업기간":"3년 이상","업종":"건설 창호","업태":"하도급","2024년매출":"약8천만","월평균매출":"","기존대출건수":"없음","기존대출총잔액":"","대출종류":"","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-30T10:00:58.383Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (9, '김소희', '01097837047', '개인사업자', '1천~3천만원', '운영자금', '인천광역시', NULL, '현재연체:예, 1년이내:예', '{"성별":"여성","연령대":"50대","사업기간":"2~3년","업종":"제조업","업태":"천막","2024년매출":"","월평균매출":"","기존대출건수":"없음","기존대출총잔액":"","대출종류":"","현재연체":"예","1년이내연체":"예","자금용도기타":""}', 'pending', '2026-07-31T01:50:31.434Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (10, '이동찬', '01062282791', '개인사업자', '1천~3천만원', '운영자금', '인천광역시', '1억8천5백', '현재연체:아니오, 1년이내:아니오', '{"성별":"남성","연령대":"60대 이상","사업기간":"3년 이상","업종":"건설업","업태":"건설 ,철강재설치,판넬","2024년매출":"2억5천7백","월평균매출":"2,000만원","기존대출건수":"4건 이상","기존대출총잔액":"1억원 이상","대출종류":"사업자대출, 담보대출, 현금서비스, 개인신용대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-07-31T05:10:41.259Z');
INSERT INTO applications (id, name, phone, job_type, loan_amount, loan_purpose, residence_type, annual_income, credit_score, message, status, created_at) VALUES (11, '손성율', '01030520025', '개인사업자', '1천~3천만원', '운영자금', '부산광역시', NULL, '현재연체:아니오, 1년이내:아니오', '{"성별":"남성","연령대":"60대 이상","사업기간":"6개월~1년","업종":"건설업","업태":"철거","2024년매출":"","월평균매출":"","기존대출건수":"","기존대출총잔액":"1,000~3,000만원","대출종류":"사업자대출","현재연체":"아니오","1년이내연체":"아니오","자금용도기타":""}', 'pending', '2026-08-03T07:31:28.135Z');
SELECT setval('applications_id_seq', 11);

-- ── site_settings ─────────────────────────────────────────
TRUNCATE TABLE site_settings RESTART IDENTITY CASCADE;
INSERT INTO site_settings (id, kakao_link, updated_at) VALUES (1, NULL, '2026-06-11T03:26:25.526Z');

-- ── telegram_settings ──────────────────────────────────────
TRUNCATE TABLE telegram_settings RESTART IDENTITY CASCADE;
